# site properties and page defaults
title: 东北大学信息检索实验室
subtitle: Northeastern University Information Retrieval Lab
description: '东北大学信息检索实验室隶属东北大学计算机科学与工程学院计算机科学系，由刘正皓副教授、于戈教授和谷峪教授共同指导，致力于信息检索与大语言模型相关研究，承担多项国家级、省部级项目，在 NeurIPS、ICLR、ACL、EMNLP、NAACL、SIGIR、KDD、WebConf、ICASSP 等国际国内顶级会议及期刊发表 70 余篇论文。课题组曾在 TREC-COVID 文档级检索比赛中获第一名；联合研发的 MiniCPM 检索增强生成组件在 MTEB 榜单中文检索效果排名第一；开源的 UltraRAG 工具获超 5k 个星标。'
url: https://neuir.github.io
baseurl: ""
header: images/school.webp
footer: images/school.webp
proofer: false
future: true

# site social media and other links
links:
  email: liuzhenghao@mail.neu.edu.cn
  google-scholar: 4vrZRk0AAAAJ
  github: NEUIR
  orcid: 0000-0003-0083-3224

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # Markdown files in /_cources
  - scope:
      type: "courses"
    values:
      layout: course

collections:
  # generate page for each member
  members:
    output: false
  # generate page for each post
  posts:
    output: true
  # generate page for each course
  courses:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
